# -*- coding: utf-8 -*-
"""Projeto Fase 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U3cNpyd9Xj3ztlw5tkxPoS7ExY44uq0s
"""

import matplotlib.pyplot as plt
# abertura e leitura do arquivo.csv
def carregar_dados() :

  arq = open("Anexo_Arquivo_Dados_Projeto_Logica_e_programacao_de_computadores.csv", "r")
  next(arq)
  dados = [] #Lista principal

  for linha in arq:
    valores = linha.split(",")

    data = valores[0].split("/") #separando a data em dia, mes e ano
    dia = int(data[0])
    mes = int(data[1])
    ano = int(data[2])
    precip = (float(valores[1]))
    tmaxima = (float(valores[2]))
    tminima = (float(valores[3]))
    # horas_insol = (float(valores[4])) - #As colunas 4 e 5 (horas insolaçao e temp. média)
    # tmedia_ano = (float(valores[5]))    #foram desconsideradas por nãoo serem solicitadas no enunciado do projeto
    um_relativa = (float(valores[6]))
    vel_vento = (float(valores[7]))

    registro = [dia, mes, ano, precip, tmaxima, tminima, um_relativa, vel_vento]

    dados.append (registro)
  arq.close()
  return dados

# Item B - Mes mais chuvoso
def mes_mais_chuvoso(dados):
 # Fazendo dicionario
    chuva_por_mes = {}

    for registro in dados:
      mes = registro[1]
      ano = registro[2]
      precip = registro [3]

      chave = str(mes)+ "/" + str(ano)

      if chave not in chuva_por_mes:
        chuva_por_mes[chave] = 0
      chuva_por_mes[chave] = chuva_por_mes[chave] + precip

    maior_precip = 0
    mes_ano = ""

    for chave in chuva_por_mes:
      if chuva_por_mes[chave]> maior_precip:
        maior_precip = chuva_por_mes[chave]
        mes_ano = chave
    return mes_ano, maior_precip

# Item C - Media da temperatura maxima
def media_minima_mes(dados, mes_escolhido):
 # Fazendo dicionario
    soma_por_ano = {}
    cont_por_ano = {}
    medias_por_ano = {}

    for registro in dados:
        mes = registro[1]
        ano = registro[2]
        tminima = registro[5]

        if ano >= 2006 and ano <= 2016 and mes == mes_escolhido:
            if ano not in soma_por_ano:
                soma_por_ano[ano] = 0
                cont_por_ano[ano] = 0

            soma_por_ano[ano] = soma_por_ano[ano] + tminima
            cont_por_ano[ano] = cont_por_ano[ano] + 1

    for ano in soma_por_ano:
        medias_por_ano[ano] = soma_por_ano[ano] / cont_por_ano[ano]

    return medias_por_ano

# Introdução do programa ao usuário
print("Este programa realiza análises de dados meteorológicos")
print("de Porto Alegre entre os anos de 1961 e 2016.")
print()
print("Deseja prosseguir?")
print("sim/nao")
print()

opcao = str(input())

# Validando a entrada inicial
while opcao != "sim" and opcao != "nao" :
 print(">> Resposta inválida. Por favor, tente novamente:")
 opcao = str(input())

# (Encerrar programa)
if opcao == "nao" :
  print("=" * 45)
  print()
  print("Encerrando programa! Até logo.")

# (Continuar programa)
else:
  dados = carregar_dados()

  # Funçao para entrada de dados do usuario e validaçao
  # (não precisar alongar o codigo com o mesmo algoritmo em caso de falha de ordem entre os anos computados pelo usuario)
  def ler_periodo():
    print ("=" * 45)
    print()

    #Input do ano e mes inicial
    mes_ini = int(input("Informe o mês inicial: "))
    while mes_ini < 1 or mes_ini > 12:
      mes_ini = int(input(">> Mês inicial inválido. Digite novamente: "))

    ano_ini = int(input("Informe o ano inicial: "))
    while ano_ini < 1961 or ano_ini > 2016:
     ano_ini = int(input(">> Ano inicial inválido. Digite novamente: "))

    print()
    print("-- data inicial: ", mes_ini,"/",ano_ini, "--")
    print()

    #Input do ano e mes final
    mes_fim = int(input("Informe o mês final: "))
    while mes_fim < 1 or mes_fim > 12:
     mes_fim = int(input(">> Mês final inválido. Digite novamente: "))

    ano_fim = int(input("Informe o ano final: "))
    while ano_fim < 1961 or ano_fim > 2016:
     ano_fim = int(input(">> Ano final inválido. Digite novamente: "))

    print()
    print("-- data final: ", mes_fim,"/",ano_fim, "--")
    print()

    return mes_ini, ano_ini, mes_fim, ano_fim

  mes_ini, ano_ini, mes_fim, ano_fim = ler_periodo()

  inicio = ano_ini * 100 + mes_ini
  fim = ano_fim * 100 + mes_fim

  #Em caso de ordem de anos inválida, chamar a funçao criada (mes_ini, ano_ini, mes_fim, ano_fim = ler_periodo())
  while inicio > fim:
    print("Período inválido. Reiniciando processo...")

    mes_ini, ano_ini, mes_fim, ano_fim = ler_periodo()

    inicio = ano_ini*100 + mes_ini
    fim = ano_fim*100 + mes_fim

  #Tipos de visualizaçoes disponiveis
  print()
  print("="*45)
  print()
  print("informe o tipo de visualização desejada:")
  print()
  print("Todos os dados - 1")
  print("Apenas a precipitaçao - 2")
  print("Apenas dados de temperatura - 3")
  print("Apenas umidade e vento no período - 4")
  tipo = int(input())
  print()

  while tipo < 1 or tipo >4:
    print("Tipo inválido. Tente novamente:")
    tipo = int(input())
  print("="*45)
  print()

  #Fazendo um cabeçalho para a quantidade de dados pedida

  if tipo == 1:
    print("DATA       | PRECIP | TMAX  | TMIN  | UMIDADE | VENTO")
  elif tipo == 2:
    print("DATA       | PRECIPITAÇÃO")
  elif tipo == 3:
    print("DATA       | TMAX  | TMIN")
  else:
    print("DATA       | UMIDADE | VENTO")
  print("=" * 90)


  # ==============================
  # Item A - visualização
  # =============================

  for registro in dados:

    dia = registro[0]
    mes = registro[1]
    ano = registro[2]
    precip = registro[3]
    tmaxima = registro[4]
    tminima = registro[5]
    um_relativa = registro[6]
    vel_vento = registro[7]

    data_registro = ano * 100 + mes #Juntando ano + mes (Ex. 199906)

    if inicio <= data_registro <= fim:

      if tipo == 1:
        print(f"{dia:<2}/{mes:<2}/{ano:<4} | Precip: {precip:<5.1f} | Máx: {tmaxima:<5.1f} | Mín: {tminima:<5.1f} | Umidade: {um_relativa:<5.1f} | Vento: {vel_vento:<5.1f}")

      elif tipo == 2:
       print(f"{dia:<2}/{mes:<2}/{ano:<4} | Precipitação: {precip:<5.1f}")

      elif tipo == 3:
        print(f"{dia:<2}/{mes:<2}/{ano:<4} | Máx: {tmaxima:<5.1f} | Mín: {tminima:<5.1f}")

      else:
        print(f"{dia:<2}/{mes:<2}/{ano:<4} | Umidade: {um_relativa:<5.1f} | Vento: {vel_vento:<5.1f}")


  print()
  print("=" * 45)
  input("Pressione ENTER para continuar para o item B...")
  print("=" * 45)

  # ===========================
  # Item B - Mês mais chuvoso
  # ===========================

  mes_ano, maior_precip = mes_mais_chuvoso(dados)

  print("Mês mais chuvoso:", mes_ano)
  print("Precipitação acumulada:", round(maior_precip, 1), "mm")

  print("=" * 45)
  input("Pressione ENTER para continuar para o item C...")
  print("=" * 45)

  # ===========================
  # Item C - Media da temperatura mínima
  # ===========================

  mes_escolhido = int(input("Informe o mês para calcular a média da temperatura mínima: "))

  while mes_escolhido < 1 or mes_escolhido > 12:
    mes_escolhido = int(input("Mês inválido. Digite novamente: "))

  medias_por_ano = media_minima_mes(dados, mes_escolhido)

  print("Médias da temperatura mínima:")
  for ano in medias_por_ano:
    print(ano, "-", round(medias_por_ano[ano], 2), "°C")


  # ===========================
  # Item D - Gráfico Matplotlib
  # ===========================


  print("=" * 45)
  input("Pressione ENTER para continuar para o item D...")
  print("=" * 45)

  anos = list(medias_por_ano.keys())
  medias = list(medias_por_ano.values())

  plt.bar(anos, medias)

  plt.title("Temperatura mínima média - mes")
  plt.xlabel("Ano")
  plt.ylabel("Temperatura (°C)")

  plt.show()


  # ===========================
  # Item E- Média geral
  # ===========================
  soma = 0

  for media in medias_por_ano.values():
    soma = soma + media

  media_geral = soma / len(medias_por_ano)

  print("Média geral:", round(media_geral,2))